In [1]:
import torch
import numpy as np
import time
device = 'cuda' if torch.cuda.is_available() else 'cpu'
print(device)

cuda


In [2]:
%%time
start_time = time.time()
zeros = torch.zeros(1,1)
end_time = time.time()

elapsed_time = end_time - start_time
print(f"{elapsed_time:.8f}")

0.01563668
CPU times: total: 0 ns
Wall time: 15.6 ms


In [28]:
probabilities = torch.tensor([0.1, 0.9])
#10 % chance for index 0 and 90% chance for index 1
samples = torch.multinomial(probabilities, num_samples=10, replacement=True)
print(samples)

tensor([1, 1, 1, 1, 1, 1, 0, 1, 1, 1])


In [33]:
tensor = torch.tensor([1, 2, 3, 4, 5])
out = torch.cat((tensor, torch.tensor([5])), dim=0)
out

tensor([1, 2, 3, 4, 5, 5])

In [36]:
out = torch.tril(torch.ones(5, 5))
out

tensor([[1., 0., 0., 0., 0.],
        [1., 1., 0., 0., 0.],
        [1., 1., 1., 0., 0.],
        [1., 1., 1., 1., 0.],
        [1., 1., 1., 1., 1.]])

In [37]:
out = torch.triu(torch.ones(5, 5))
out

tensor([[1., 1., 1., 1., 1.],
        [0., 1., 1., 1., 1.],
        [0., 0., 1., 1., 1.],
        [0., 0., 0., 1., 1.],
        [0., 0., 0., 0., 1.]])

In [39]:
out = torch.zeros(5, 5).masked_fill(torch.tril(torch.ones(5, 5)) == 0, float('-inf'))
out

tensor([[0., -inf, -inf, -inf, -inf],
        [0., 0., -inf, -inf, -inf],
        [0., 0., 0., -inf, -inf],
        [0., 0., 0., 0., -inf],
        [0., 0., 0., 0., 0.]])

In [40]:
torch.exp(out)

tensor([[1., 0., 0., 0., 0.],
        [1., 1., 0., 0., 0.],
        [1., 1., 1., 0., 0.],
        [1., 1., 1., 1., 0.],
        [1., 1., 1., 1., 1.]])

In [42]:
input = torch.zeros(2, 3, 4)
out = input.transpose(0, 2)
out.shape

torch.Size([4, 3, 2])

In [48]:
tensor1 = torch.tensor([91, 42, 63])
tensor2 = torch.tensor([14, 48, 13])
tensor3 = torch.tensor([49, 12, 39])

out = torch.stack([tensor1, tensor2, tensor3])
out

tensor([[91, 42, 63],
        [14, 48, 13],
        [49, 12, 39]])

In [49]:
import torch.nn as nn
sample = torch.tensor([10., 10., 10.])
linear = nn.Linear(3, 3, bias=False)
print(linear(sample))

tensor([-7.1521,  3.1918,  6.6884], grad_fn=<SqueezeBackward4>)


In [51]:
import torch.nn.functional as F

tensor1 = torch.tensor([1.0, 2.0, 3.0])

#apply softmax using torch.nn.functional.softmax()
softmax_output = F.softmax(tensor1, dim=0)

print(softmax_output)

tensor([0.0900, 0.2447, 0.6652])


In [56]:
a = torch.tensor([[4, 5], [5, 6], [7, 8]])
b = torch.tensor([[2, 4, 5], [5, 6, 9]])
print(a @ b)

tensor([[ 33,  46,  65],
        [ 40,  56,  79],
        [ 54,  76, 107]])


In [84]:
int64 = torch.randint(5, (3, 2)).float()
float32 = torch.rand(2, 3)
print(int64)
print(float32)
print(torch.matmul(int64, float32))

tensor([[4., 1.],
        [0., 3.],
        [3., 2.]])
tensor([[0.2781, 0.4404, 0.7708],
        [0.8803, 0.6592, 0.8050]])
tensor([[1.9925, 2.4209, 3.8884],
        [2.6410, 1.9777, 2.4151],
        [2.5948, 2.6397, 3.9226]])
