In [1]:
import torch

In [2]:
randint = torch.randint(-100, 100, (6,))
randint

tensor([ 66,  -9,  61, -63, -48,  58])

In [4]:
tensor = torch.tensor([[.1, 1.2], [2.2, 3.1], [4.9, 5.2]])
tensor

tensor([[0.1000, 1.2000],
        [2.2000, 3.1000],
        [4.9000, 5.2000]])

In [5]:
zeros = torch.zeros(2,3)
zeros

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [9]:
ones = torch.ones(3,4)
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [11]:
input = torch.empty(2,3)
input

tensor([[8.9082e-39, 1.0194e-38, 9.1837e-39],
        [4.6837e-39, 6.9796e-39, 9.0000e-39]])

In [13]:
arange = torch.arange(5)
arange

tensor([0, 1, 2, 3, 4])

In [14]:
linspace = torch.linspace(3, 10, steps=5)
linspace

tensor([ 3.0000,  4.7500,  6.5000,  8.2500, 10.0000])

In [15]:
logspace = torch.logspace(3, 10, steps=5)
logspace

tensor([1.0000e+03, 5.6234e+04, 3.1623e+06, 1.7783e+08, 1.0000e+10])

In [16]:
eye = torch.eye(5)
eye

tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])

In [19]:
a = torch.empty((2,3), dtype=torch.int64)
print(a)
empty_like = torch.empty_like(a)
empty_like

tensor([[28710924373327984, 26740556586287209, 27303510834217060],
        [25896196080664693, 32651591226556520, 12948368627204207]])


tensor([[0, 0, 0],
        [0, 0, 0]])